defaults: &defaults
  enabled:
    - facebook
    - twitter
    - google_plus
    - linkedin
    - stack_overflow
    - github
    - bitbucket
    - youtube
    - tumblr
    - pinterest
    - instagram
    - flickr
    - foursquare

  highlighted:
    - facebook
    - twitter
    - google_plus
    - linkedin
    - stack_overflow
    - github
    - bitbucket

  bitbucket:
    icon: bitbucket
    name: Bitbucket
    placeholder: 'http://bitbucket.org/username'

  facebook:
    icon: facebook
    name: Facebook
    placeholder: 'https://facebook.com/username'
    pattern: 'facebook.com/username|(http|https)://facebook.com/app_scoped_user_id/userid'

  flickr:
    icon: flickr
    name: Flickr
    placeholder: 'https://flickr.com/photos/username'

  foursquare:
    icon: foursquare
    name: Foursquare
    placeholder: 'https://foursquare.com/username'

  github:
    icon: github-alt
    name: GitHub
    placeholder: 'https://github.com/username'

  google_plus:
    icon: google-plus
    name: Google +
    placeholder: 'https://plus.google.com/userid'

  instagram:
    icon: instagram
    name: Instagram
    placeholder: 'https://instagram.com/username'

  linkedin:
    icon: linkedin
    name: LinkedIn
    placeholder: 'https://linkedin.com/in/username'

  pinterest:
    icon: pinterest
    name: Pinterest
    placeholder: 'https://pinterest.com/username'

  stack_overflow:
    icon: stack-overflow
    name: Stack Overflow
    placeholder: 'https://stackoverflow.com/users/userid'

  tumblr:
    icon: tumblr
    name: Tumblr
    placeholder: 'https://username.tumblr.com'

  twitter:
    icon: twitter
    name: Twitter
    placeholder: 'https://twitter.com/username'

  youtube:
    icon: youtube-play
    name: YouTube
    placeholder: 'https://youtube.com/username'

fiit_development:
  <<: *defaults

fiit_test:
  <<: *defaults

fiit_staging:
  <<: *defaults

fiit_demo:
  <<: *defaults

fiit_production:
  <<: *defaults

edx_development:
  <<: *defaults

edx_test:
  <<: *defaults

edx_staging:
  <<: *defaults

edx_demo:
  <<: *defaults

edx_production:
  <<: *defaults

lugano_production:
  <<: *defaults

novisad_production:
  <<: *defaults